{{- if eq "" .Values.codeserver.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "code-server.fullname" . }}
  labels:
    app: "{{ template "code-server.name" . }}"
    chart: "{{ template "code-server.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.codeserver.password) }}
  codeserver-password: "{{ .Values.codeserver.password | b64enc }}"
  {{- else }}
  codeserver-password: {{ required "Code server Password is required!" .Values.codeserver.password }}
  {{- end }}
{{- end }}